version: "3"
services:
  back:
    container_name: back-nodejs
    # to build an image based on Dockerfile
    # it looks in this folder to find Dockerfile to build an image
    build: ./back
    ports:
      - 8000:8000 # Nous exposons le port 8800

  front:
    container_name: front-reactjs
    # to build an image based on Dockerfile
    # it looks in this folder to find Dockerfile to build an image
    build: ./front
    # the port that we want to publish for frontend
    ports:
      - 3000:3000
    # add bind mount volume to keep have updated source code
    volumes:
      - ./front/src:/app/src
    # # it will start our frontend container once backend-container is  up and running.
    depends_on:
      - backend